openapi: 3.0.0
info:
  title: RipleyTech Schedule Coverage API
  version: "1.0.0"
paths:
  /api/schedule/coverage:
    post:
      summary: Obtener agendas de despacho con cobertura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: string
                commune:
                  type: string
              required:
                - products
                - commune
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        product:
                          type: string
                        schedules:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              courier:
                                type: string
                              serviceType:
                                type: string
                              deliveryMethod:
                                type: string
                              cutTime:
                                type: array
                                items:
                                  type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        product:
                          type: string
                        error:
                          type: string
        "500":
          description: Error interno del servidor
